"""
debate_engine_cloud.py
======================
Debate engine using 'instructor' for guaranteed structured outputs.
Backed by Azure AI Services or a local Ollama instance.
"""

import json
import os
import random
import re
import concurrent.futures
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Tuple, Type, TypeVar, Union, Callable

import instructor
from openai import OpenAI, AzureOpenAI
from pydantic import BaseModel, Field
from dotenv import load_dotenv

load_dotenv()

from config import AGENT_LIBRARY, PHILOSOPHER_LIBRARY, SYSTEM_PROMPT


TOKEN_USAGE_LOG: List[Dict[str, Any]] = []
TEAM_MAX_REVIEW_ATTEMPTS = 3
TEAM_MIN_APPROVAL_SCORE = 8
TEAM_INTERNAL_CHAR_LIMIT = 1800
_AZURE_API_VERSION = "2024-12-01-preview"
FREE_TOPIC_SYSTEM_PROMPT = (
    "You are not participating in a debate. "
    "You are part of a philosopher-inspired opinion team. "
    "Give a thoughtful opinion on the user's given input. "
    "If the input naturally supports opposing positions, consider one supportive/pro "
    "perspective and one skeptical/contra perspective. "
    "If it does not, do not force a pro/contra frame; provide a useful, direct opinion instead. "
    "Be concise, logically consistent, and stay on topic."
)


def _audio_transcription_enabled() -> bool:
    try:
        import streamlit as st
    except Exception:
        return True

    for key in ("_dp_audio_transcription", "_pref_audio_transcription", "audio_transcription"):
        if key in st.session_state:
            return bool(st.session_state[key])
    return True


# ---------------------------------------------------------------------------
# Pydantic Models for Structured Output
# ---------------------------------------------------------------------------

class PhilosopherResponse(BaseModel):
    """The final public response of a philosopher."""
    reasoning: str = Field(description="Step-by-step thinking process and internal drafting for the argument. Write this first. Use markdown if helpful, but do NOT wrap the text in markdown code blocks.")
    argument: str = Field(description="The philosophical argument text. ALWAYS format nicely using standard markdown: use double newlines (\\n\\n) for paragraphs, bold for emphasis, and bullet points for lists. Do NOT wrap the text in markdown code blocks.")

class JudgeResult(BaseModel):
    """The structured result of the judge."""
    reasoning: str = Field(description="Step-by-step thinking process and explanation of the verdict. Write this first. Format with markdown, use double newlines for paragraphs. Do NOT wrap in markdown code blocks.")
    winner: str = Field(description="Exact name of the winning philosopher.")
    scores: Dict[str, Dict[str, float]] = Field(description="Metrics for each speaker.")

class TeamCandidatePlan(BaseModel):
    """Internal plan generated by a strategist."""
    reasoning: str = Field(description="Your step-by-step thought process and planning reasoning. Write this first. Do NOT wrap in markdown code blocks.")
    candidate_id: str
    plan_summary: str = Field(description="The complete proposed argument or opinion response text matching your persona and strategy. Do NOT wrap in markdown code blocks.")

class TeamSelection(BaseModel):
    """Selection logic from the critic."""
    selection_reasoning: str = Field(description="Your step-by-step selection reasoning. Write this first. Do NOT wrap in markdown code blocks.")
    selected_candidate: str = Field(description="A, B, or COMBINE")
    revision_guidance: str

class TeamReview(BaseModel):
    """Review of a drafted response."""
    critique: str = Field(description="Detailed critique and review reasoning of the draft. Write this first. Do NOT wrap in markdown code blocks.")
    score: int = Field(ge=0, le=10)
    approved: bool
    revision_guidance: str

class SummaryResponse(BaseModel):
    """The final debate summary."""
    summary: str = Field(description="The debate summary text. ALWAYS format nicely using standard markdown: use double newlines (\\n\\n) for paragraphs. Do NOT wrap in markdown code blocks.")

# ---------------------------------------------------------------------------
# Client Routing
# ---------------------------------------------------------------------------

T = TypeVar("T", bound=BaseModel)

def _get_instructor_client(provider: str, model: str = "") -> Tuple[Any, Any, Any]:
    """Returns (client, mode, raw_client)."""
    if provider == "local":
        base_url = os.getenv("OLLAMA_BASE_URL", "http://localhost:11434/v1").rstrip("/")
        raw_client = OpenAI(base_url=base_url, api_key="ollama", timeout=180.0)
        client = instructor.from_openai(raw_client, mode=instructor.Mode.JSON)
        return client, instructor.Mode.JSON, raw_client
    else:
        endpoint = os.getenv("CUSTOM_API_BASE_URL", "").rstrip("/")
        api_key = os.getenv("CUSTOM_API_KEY", "")
        if not endpoint or not api_key:
            raise ValueError("Azure credentials missing in .env")
        
        raw_client = AzureOpenAI(
            api_key=api_key,
            api_version=os.getenv("AZURE_API_VERSION", _AZURE_API_VERSION),
            azure_endpoint=endpoint,
            timeout=180.0
        )
        
        # Phi-4 and some other models on Azure AI Services often fail with TOOLS mode.
        # MD_JSON is much more reliable for non-GPT models.
        if "Phi-4" in model or "mistral" in model.lower() or "Llama" in model:
            client = instructor.from_openai(raw_client, mode=instructor.Mode.MD_JSON)
            return client, instructor.Mode.MD_JSON, raw_client
        
        client = instructor.from_openai(raw_client)
        return client, None, raw_client

def _generate_mock_template(model_cls: Type[BaseModel]) -> dict:
    template = {}
    for name, field in model_cls.model_fields.items():
        desc = field.description or ""
        ann = field.annotation
        # Strip Optional[...] wrapper if present
        if hasattr(ann, "__origin__") and ann.__origin__ is Union:
            args = ann.__args__
            args = [a for a in args if a is not type(None)]
            if len(args) == 1:
                ann = args[0]
                
        if ann == str:
            if "winner" in name:
                template[name] = "Philosopher A"
            else:
                template[name] = f"[Your {name} here]"
        elif ann == int or ann == float:
            template[name] = 8.0 if name == "score" else 0.0
        elif ann == bool:
            template[name] = True
        elif hasattr(ann, "__origin__") and ann.__origin__ is dict:
            sub_type = ann.__args__[1]
            if hasattr(sub_type, "__origin__") and sub_type.__origin__ is dict:
                template[name] = {
                    "Philosopher A": {
                        "logical_validity": 8.0,
                        "argument_strength": 8.0,
                        "counterargument_handling": 8.0,
                        "clarity": 8.0,
                        "relevance": 8.0,
                        "total": 8.0
                    },
                    "Philosopher B": {
                        "logical_validity": 7.0,
                        "argument_strength": 7.0,
                        "counterargument_handling": 7.0,
                        "clarity": 7.0,
                        "relevance": 7.0,
                        "total": 7.0
                    }
                }
            else:
                template[name] = {"key": 0.0}
        else:
            template[name] = "Example value"
    return template

def clean_and_verify_text(text: str, user_prompt: str, field_name: str, raw_client: Any, model: str) -> str:
    cleaned = text.strip()
    
    # Remove surrounding markdown code blocks that LLMs mistakenly add to string fields
    cleaned = re.sub(r"^```(?:markdown|json|text)?\s*", "", cleaned, flags=re.IGNORECASE)
    cleaned = re.sub(r"\s*```$", "", cleaned)
    
    # Strip outer brackets ONLY if they wrap the entire text (avoid destroying markdown links or citations)
    if cleaned.startswith("[") and cleaned.endswith("]"):
        # Simple heuristic: if it looks like a wrapped response (e.g. [My argument...]) and not a markdown link
        if "](" not in cleaned:
            cleaned = cleaned[1:-1].strip()
    
    placeholders = [
        "step-by-step thinking process",
        "explanation of the verdict",
        "internal drafting for the argument",
        "detailed explanation and analysis",
        "detailed philosophical argument",
        "write this first",
        "example text value",
    ]
    
    is_placeholder = any(p in cleaned.lower() for p in placeholders)
    
    if is_placeholder:
        try:
            # Query the model directly for actual text without JSON constraints
            prompt = f"Provide a realistic, brief, 1-2 sentence response for the field '{field_name}'."
            if "reasoning" in field_name:
                prompt = "Write a brief 1-2 sentence explanation of the reasoning/verdict for the debate. Do not write JSON, do not use square brackets, just output raw text."
            elif "argument" in field_name:
                prompt = "Write a brief 1-2 sentence argument presenting this stance. Do not write JSON, do not use square brackets, just output raw text."
                
            res = raw_client.chat.completions.create(
                model=model,
                messages=[
                    {"role": "system", "content": "You are a professional debater and judge. Output only your raw response text directly, without brackets or quotes."},
                    {"role": "user", "content": f"Context prompt was: {user_prompt}\n\nTask: {prompt}"}
                ],
                temperature=0.7,
                max_tokens=150
            )
            val = res.choices[0].message.content.strip()
            # Strip potential markdown code blocks or brackets from the new response
            val = re.sub(r'```.*?```', '', val, flags=re.DOTALL).strip()
            val = val.replace("[", "").replace("]", "").strip()
            if len(val) > 10 and not any(p in val.lower() for p in placeholders):
                return val
        except Exception:
            pass
            
    return cleaned

def _clean_response_object(obj: Any, user_prompt: str, raw_client: Any, model: str) -> Any:
    if obj is None or isinstance(obj, str):
        return obj
    try:
        for field_name in obj.model_fields:
            val = getattr(obj, field_name, None)
            if isinstance(val, str):
                cleaned_val = clean_and_verify_text(val, user_prompt, field_name, raw_client, model)
                setattr(obj, field_name, cleaned_val)
    except Exception:
        pass
    return obj

def _usage_value(usage: Any, *keys: str) -> int:
    if not usage:
        return 0

    usage_dict = usage if isinstance(usage, dict) else None
    if usage_dict is None and hasattr(usage, "model_dump"):
        try:
            usage_dict = usage.model_dump()
        except Exception:
            usage_dict = None

    for key in keys:
        value = usage_dict.get(key) if usage_dict else getattr(usage, key, None)
        if value is None:
            continue
        try:
            return int(value)
        except (TypeError, ValueError):
            continue

    return 0


def _estimate_token_count(text: str) -> int:
    text = str(text or "").strip()
    if not text:
        return 0

    # Lightweight approximation for local/streaming backends that omit usage.
    return max(1, round(len(text) / 4))


def _chunk_usage(chunk: Any) -> Any:
    if isinstance(chunk, dict):
        return chunk.get("usage")
    return getattr(chunk, "usage", None)


def _chunk_token(chunk: Any) -> str:
    choices = chunk.get("choices", []) if isinstance(chunk, dict) else getattr(chunk, "choices", [])
    if not choices:
        return ""

    delta = choices[0].get("delta", {}) if isinstance(choices[0], dict) else getattr(choices[0], "delta", None)
    if isinstance(delta, dict):
        return delta.get("content") or ""
    return getattr(delta, "content", None) or ""


def _stream_completion(raw_client: Any, params: Dict[str, Any]):
    stream_params = {**params, "stream": True, "stream_options": {"include_usage": True}}
    try:
        return raw_client.chat.completions.create(**stream_params)
    except Exception as exc:
        message = str(exc).lower()
        if "stream_options" not in message and "stream options" not in message:
            raise
        return raw_client.chat.completions.create(**{**params, "stream": True})


def _completion_text(value: Any) -> str:
    if value is None:
        return ""
    if hasattr(value, "model_dump_json"):
        try:
            return value.model_dump_json()
        except Exception:
            pass
    return str(value)


def chat_completion(
    system_prompt: str,
    user_prompt: str,
    *,
    provider: str = "",
    model: str = "",
    response_model: Optional[Type[T]] = None,
    stream_generator: bool = False,
    stream_callback: Optional[Callable[[str], None]] = None,
    temperature: Optional[float] = None,
) -> Any:
    if not provider or not model:
        return "[ERROR] Missing model/provider"

    is_small_model = provider == "local" or any(m in model.lower() for m in ["phi", "llama", "mistral", "qwen", "3.2", "1b", "3b", "8b"])

    try:
        client, mode, raw_client = _get_instructor_client(provider, model)

        # Determine temperature — caller may override via the temperature kwarg
        if temperature is None:
            if response_model:
                temperature = 0.1 if is_small_model else 0.2
            else:
                temperature = 0.7

        # Inject JSON template example for smaller models
        if response_model and is_small_model:
            mock_example = _generate_mock_template(response_model)
            example_json = json.dumps(mock_example, indent=2)
            user_prompt = (
                f"{user_prompt}\n\n"
                f"IMPORTANT: You MUST respond ONLY with a valid JSON object matching the exact structure shown below. "
                f"Replace the example placeholder strings with your actual generated, properly formatted content! "
                f"Do not add any text before or after the JSON block.\n"
                f"```json\n{example_json}\n```"
            )

        params = {
            "model": model,
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt},
            ],
            "temperature": temperature,
        }
        
        # Phi-4 and reasoning models can be very verbose
        if "Phi-4" in model:
            params["max_tokens"] = 4000 

        if response_model:
            params["response_model"] = response_model
            params["max_retries"] = 3
            
            # Call completion
            response = client.chat.completions.create(**params)
            
            # Track usage
            usage = getattr(response, "_raw_response", None)
            if usage and hasattr(usage, "usage"):
                 _record_usage(user_prompt, provider, model, usage.usage, _completion_text(response))
            else:
                 _record_usage(user_prompt, provider, model, None, _completion_text(response))
                 
            # Clean response fields
            if not isinstance(response, str):
                response = _clean_response_object(response, user_prompt, raw_client, model)
            
            return response
        else:
            if stream_generator or stream_callback:
                raw_res = _stream_completion(raw_client, params)
                
                if stream_generator:
                    def generator():
                        response_text = ""
                        stream_usage = None
                        for chunk in raw_res:
                            stream_usage = _chunk_usage(chunk) or stream_usage
                            token = _chunk_token(chunk)
                            if token:
                                response_text += token
                                if stream_callback:
                                    stream_callback(token)
                                yield token
                        _record_usage(user_prompt, provider, model, stream_usage, response_text)
                    return generator()
                else:
                    response_text = ""
                    stream_usage = None
                    for chunk in raw_res:
                        stream_usage = _chunk_usage(chunk) or stream_usage
                        token = _chunk_token(chunk)
                        if token:
                            response_text += token
                            stream_callback(token)
                    _record_usage(user_prompt, provider, model, stream_usage, response_text)
                    return response_text.strip()
            else:
                # Bypass instructor entirely for raw text
                raw_res = raw_client.chat.completions.create(**params)
                content = raw_res.choices[0].message.content.strip()
                _record_usage(user_prompt, provider, model, getattr(raw_res, "usage", None), content)
                return content
    except Exception as exc:
        # Fallback for models that output reasoning tags <think>...</think>
        # or fail instructor's default validation (often true for small local models).
        if response_model:
            try:
                mock_template = _generate_mock_template(response_model)
                template_json = json.dumps(mock_template, indent=2)
                fallback_prompt = (
                    f"{user_prompt}\n\n"
                    f"IMPORTANT: Output ONLY a valid JSON object. Do not include any reasoning or extra text.\n"
                    f"Follow this exact JSON structure (replace the placeholders with your actual evaluation):\n"
                    f"```json\n{template_json}\n```"
                )
                
                raw_res = raw_client.chat.completions.create(
                    model=model,
                    messages=[
                        {"role": "system", "content": system_prompt},
                        {"role": "user", "content": fallback_prompt},
                    ],
                    temperature=0.3,
                    max_tokens=params.get("max_tokens", 2000)
                )
                content = raw_res.choices[0].message.content
                # Strip <think> blocks
                content = re.sub(r'<think>.*?</think>', '', content, flags=re.DOTALL).strip()
                # Find JSON block
                json_match = re.search(r'```json\s*(.*?)\s*```', content, re.DOTALL) or \
                             re.search(r'({.*})', content, re.DOTALL)
                
                if json_match:
                    json_str = json_match.group(1)
                    try:
                        parsed = response_model.model_validate_json(json_str)
                    except Exception:
                        data = json.loads(json_str)
                        if isinstance(data, dict):
                            # 1. Lift keys from 'properties' if the model output the schema itself
                            if "properties" in data and isinstance(data["properties"], dict):
                                for k, v in data["properties"].items():
                                    if k not in data or data[k] is None:
                                        data[k] = v
                            
                            # 2. Fix type mismatches (e.g. list/dict where string is expected)
                            for field_name, field_info in response_model.model_fields.items():
                                if field_name in data:
                                    val = data[field_name]
                                    if field_info.annotation is str:
                                        if isinstance(val, list):
                                            data[field_name] = "\n".join(str(item) for item in val)
                                        elif isinstance(val, dict):
                                            data[field_name] = json.dumps(val)
                                        elif val is None:
                                            data[field_name] = ""
                                        else:
                                            data[field_name] = str(val)
                        parsed = response_model.model_validate(data)

                    _record_usage(user_prompt, provider, model, getattr(raw_res, "usage", None), _completion_text(parsed))
                    # Clean parsed fields
                    parsed = _clean_response_object(parsed, user_prompt, raw_client, model)
                    return parsed
            except Exception as nested_exc:
                return f"[ERROR] API failed: {exc} (Fallback also failed: {nested_exc})"

        return f"[ERROR] API failed: {exc}"

def _record_usage(prompt: str, provider: str, model: str, usage: Any, completion_text: str = ""):
    label = "Model call"
    if prompt.lstrip().startswith("Summarize this "): label = "Summary"
    elif "Judge" in prompt or "judge" in prompt: label = "Judge"
    elif "Critic" in prompt: label = "Critic"
    elif "Strategist" in prompt: label = "Strategist"
    elif "Role: Speaker" in prompt: label = "Speaker"

    pt = _usage_value(usage, "prompt_tokens", "prompt_eval_count", "input_tokens")
    ct = _usage_value(usage, "completion_tokens", "eval_count", "output_tokens")
    tt = _usage_value(usage, "total_tokens")
    estimated = False

    if not (pt or ct or tt):
        pt = _estimate_token_count(prompt)
        ct = _estimate_token_count(completion_text)
        estimated = bool(pt or ct)

    if not tt:
        tt = pt + ct

    entry = {
        "call": label,
        "provider": provider,
        "model": model,
        "prompt_tokens": pt,
        "completion_tokens": ct,
        "total_tokens": tt
    }
    if estimated:
        entry["estimated"] = True

    TOKEN_USAGE_LOG.append(entry)

def get_client_and_model():
    base_url = os.getenv("CUSTOM_API_BASE_URL", "")
    if not base_url or not os.getenv("CUSTOM_API_KEY"):
        return None, None, "Azure not configured"
    return base_url, "ready", None

def reset_token_usage(): TOKEN_USAGE_LOG.clear()
def get_token_usage(): return list(TOKEN_USAGE_LOG)

# ---------------------------------------------------------------------------
# Debate Logic
# ---------------------------------------------------------------------------

@dataclass
class TeamSpeaker:
    name: str
    image: str
    side: str = ""

@dataclass
class DebateAgent:
    key: str
    name: str
    goal: str
    style: str
    philosopher: str = ""
    philosopher_stance: str = ""
    image: str = ""
    side: str = ""
    agent_provider: str = ""
    agent_model: str = ""
    team_config: Dict[str, Any] = field(default_factory=dict)

    def _team_roles_for_trace(self) -> Dict[str, Dict[str, str]]:
        roles = {}
        for role_key, role in self.team_config.items():
            if role_key == "max_review_attempts" or not isinstance(role, dict):
                continue
            roles[role_key] = {
                "label": str(role.get("label", role_key)),
                "philosopher": str(role.get("philosopher_name", "-")),
                "strategy": str(role.get("strategy", "-")),
            }
        return roles

    def _system_prompt(self) -> str:
        return FREE_TOPIC_SYSTEM_PROMPT if self.side == "Free Topic" else SYSTEM_PROMPT

    def _team_context(self, topic, history, round_idx, strategy):
        is_free = self.side == "Free Topic"
        history_label = "Start of discussion." if is_free else "Start of debate."
        if is_free:
            return f"""
            User input: {topic}
            Round: {round_idx}
            Mode: Free question opinion mode
            Persona: {self.philosopher}
            Style: {self.style}
            Strategy: {strategy}
            Task frame: Give your opinion on the given input. If the input allows it,
            consider one supportive/pro and one skeptical/contra angle. Do not force
            a debate when the input is open-ended, personal, descriptive, or one-sided.
            History: {history or history_label}
            """
        return f"""
        Topic: {topic}
        Round: {round_idx}
        Side: {self.side}
        Persona: {self.philosopher}
        Style: {self.style}
        Strategy: {strategy}
        History: {history or history_label}
        """

    def _respond_with_team(
        self,
        topic,
        history,
        round_idx,
        strategy,
        max_words,
        on_step=None,
        on_token=None,
        on_draft_start=None,
    ):
        trace = {
            "calls": [],
            "candidates": [],
            "selection": {},
            "reviews": [],
            "revisions": [],
            "approved": False,
            "final_score": 0,
            "team_roles": self._team_roles_for_trace(),
        }
        
        # 1. Fetch Philosopher Info for each role
        from config import PHILOSOPHER_LIBRARY
        
        def get_philosopher_info(role_key, default_key):
            role_cfg = self.team_config.get(role_key, {})
            p_key = role_cfg.get("philosopher_key", default_key)
            p_info = PHILOSOPHER_LIBRARY.get(p_key, {})
            return {
                "key": p_key,
                "name": p_info.get("name", self.philosopher),
                "style": p_info.get("style", self.style),
                "stance": p_info.get("stance", self.philosopher_stance),
                "strategy": role_cfg.get("strategy", strategy),
                "image": p_info.get("image", "")
            }
        
        info_a = get_philosopher_info("agent_a", "socrates")
        info_b = get_philosopher_info("agent_b", "nietzsche")
        info_rev = get_philosopher_info("reviewer", "aristotle")

        # 2. Generate Candidates (Strategists A & B) and Review / Refine
        is_free = self.side == "Free Topic"
        history_label = "Start of discussion." if is_free else "Start of debate."
        
        current_draft = ""
        approved_arg = ""
        counter_arg = ""
        max_attempts = self.team_config.get("max_review_attempts", TEAM_MAX_REVIEW_ATTEMPTS)
        speaker_agent = TeamSpeaker(name=info_a["name"], image=info_a["image"], side=self.side)
        
        for attempt in range(1, max_attempts + 1):
            # 2.1. Generate Candidate Pro-Argument (Strategist A)
            if on_step:
                on_step(f"Strategist A ({info_a['name']}) drafting pro-argument (Attempt {attempt})...")
            
            guidance_context = ""
            if attempt > 1:
                last_review = trace["reviews"][-1]
                guidance_context = f"\nPrevious Critic Revision Guidance: {last_review.get('revision_guidance', '')}\nPlease revise the argument to address this feedback."
            
            if is_free:
                strat_context_a = f"""
                User input: {topic}
                Round: {round_idx}
                Mode: Free question opinion mode
                Persona: {info_a['name']}
                Style: {info_a['style']}
                Stance: {info_a['stance']} (Pro/Supporting)
                Strategy: {info_a['strategy']}
                History: {history or history_label}{guidance_context}
                """
                task_desc_a = "Write a complete proposed opinion response supporting the topic/input from your perspective. Output JSON only."
            else:
                strat_context_a = f"""
                Topic: {topic}
                Round: {round_idx}
                Side: {self.side}
                Persona: {info_a['name']}
                Style: {info_a['style']}
                Stance: Supporting the {self.side} side of the debate
                Strategy: {info_a['strategy']}
                History: {history or history_label}{guidance_context}
                """
                task_desc_a = f"Write a complete proposed argument supporting the {self.side} side of the debate. Output JSON only."
            
            prompt_a = f"{strat_context_a}\nRole: Strategist ({info_a['name']})\nTask: {task_desc_a}"
            res_a = chat_completion(
                system_prompt=SYSTEM_PROMPT,
                user_prompt=prompt_a,
                provider=self.agent_provider,
                model=self.agent_model,
                response_model=TeamCandidatePlan
            )
            if isinstance(res_a, str):
                return {"text": f"[ERROR] Strategist A failed: {res_a}", "team_trace": trace}
            
            cand_dict_a = res_a.model_dump()
            cand_dict_a["id"] = f"A (Attempt {attempt})"
            cand_dict_a["role_philosopher"] = info_a["name"]
            cand_dict_a["role_strategy"] = info_a["strategy"]
            trace["candidates"].append(cand_dict_a)
            trace["calls"].append(f"Strategist A Attempt {attempt} ({info_a['name']})")
            
            pro_arg = res_a.plan_summary

            # 2.2. Generate Counterargument (Strategist B)
            if on_step:
                on_step(f"Strategist B ({info_b['name']}) drafting contra-argument (Attempt {attempt})...")
            
            if is_free:
                strat_context_b = f"""
                User input: {topic}
                Round: {round_idx}
                Mode: Free question opinion mode
                Persona: {info_b['name']}
                Style: {info_b['style']}
                Stance: Counter/Opposing the Pro-Argument
                Strategy: {info_b['strategy']}
                History: {history or history_label}
                Proposed Pro-Argument to counter: {pro_arg}
                """
                task_desc_b = "Write a strong counterargument refuting, criticizing, or exposing weaknesses in the Proposed Pro-Argument. Output JSON only."
            else:
                strat_context_b = f"""
                Topic: {topic}
                Round: {round_idx}
                Side: {self.side}
                Persona: {info_b['name']}
                Style: {info_b['style']}
                Stance: Opposing/Countering the {self.side} side of the debate
                Strategy: {info_b['strategy']}
                History: {history or history_label}
                Proposed Pro-Argument to counter: {pro_arg}
                """
                task_desc_b = f"Write a strong counterargument refuting, criticizing, or exposing weaknesses in the Proposed Pro-Argument for the {self.side} side of the debate. Output JSON only."
            
            prompt_b = f"{strat_context_b}\nRole: Strategist ({info_b['name']})\nTask: {task_desc_b}"
            res_b = chat_completion(
                system_prompt=SYSTEM_PROMPT,
                user_prompt=prompt_b,
                provider=self.agent_provider,
                model=self.agent_model,
                response_model=TeamCandidatePlan
            )
            if isinstance(res_b, str):
                return {"text": f"[ERROR] Strategist B failed: {res_b}", "team_trace": trace}
            
            cand_dict_b = res_b.model_dump()
            cand_dict_b["id"] = f"B (Attempt {attempt})"
            cand_dict_b["role_philosopher"] = info_b["name"]
            cand_dict_b["role_strategy"] = info_b["strategy"]
            trace["candidates"].append(cand_dict_b)
            trace["calls"].append(f"Strategist B Attempt {attempt} ({info_b['name']})")
            
            counter_arg = res_b.plan_summary

            # 2.3. Critic Evaluates both (Critic & Speaker)
            if on_step:
                on_step(f"Critic ({info_rev['name']}) comparing arguments (Attempt {attempt})...")
            
            rev_context = f"""
            Topic/Input: {topic}
            Round: {round_idx}
            Side: {self.side}
            Persona: {info_rev['name']}
            Style: {info_rev['style']}
            Stance: {info_rev['stance']}
            Strategy: {info_rev['strategy']}
            History: {history or history_label}
            """
            
            review_task = (
                f"Compare the proposed pro-argument by {info_a['name']} against the counterargument by {info_b['name']}.\n"
                f"Pro-Argument: {pro_arg}\n"
                f"Counterargument: {counter_arg}\n"
                f"Determine if the pro-argument is stronger/convincing enough to withstand the counterargument (approved=True, score >= {TEAM_MIN_APPROVAL_SCORE}).\n"
                f"Critique Guideline: Be highly critical and rigorous! Do not hesitate to reject the argument if it has logical loopholes, style inconsistencies, or fails to fully address the counterargument. A score of {TEAM_MIN_APPROVAL_SCORE} or above requires exceptional quality.\n"
                f"If the pro-argument is weaker or vulnerable to the counterargument, reject it (approved=False, score < {TEAM_MIN_APPROVAL_SCORE}) and write clear revision guidance on how Strategist A should improve/strengthen it.\n"
                f"Output JSON only."
            )
            
            prompt_rev = f"{rev_context}\nRole: Critic ({info_rev['name']})\nTask: {review_task}"
            review_res = chat_completion(
                system_prompt=SYSTEM_PROMPT,
                user_prompt=prompt_rev,
                provider=self.agent_provider,
                model=self.agent_model,
                response_model=TeamReview
            )
            
            if isinstance(review_res, str):
                rev_dict = {
                    "critique": f"Critique could not be parsed as JSON: {review_res}",
                    "score": 10,
                    "approved": True,
                    "revision_guidance": "None",
                    "attempt": attempt
                }
            else:
                rev_dict = review_res.model_dump()
                rev_dict["attempt"] = attempt
            
            trace["reviews"].append(rev_dict)
            trace["final_score"] = rev_dict["score"]
            trace["approved"] = rev_dict["approved"]
            trace["selection"] = {
                "selected_candidate": "A",
                "selection_reasoning": f"Compared Strategist A (Attempt {attempt}) pro-argument against Strategist B (Attempt {attempt}) counterargument. Pro-argument is {'stronger' if rev_dict['approved'] else 'weaker'}.",
                "candidate_scores": {
                    f"Strategist A (Attempt {attempt})": {
                        "score": rev_dict["score"]
                    }
                }
            }
            trace["calls"].append(f"Critic Evaluation Attempt {attempt} ({info_rev['name']})")
            
            approved_arg = pro_arg
            
            if rev_dict["approved"]:
                break
            
            trace["revisions"].append({"attempt": attempt, "plan_summary": f"Revision based on counterargument and critic feedback."})

        # 3. Final Speaker Presentation (Speaker/Moderator is bypassed; Strategist A is shown directly)
        if on_step:
            on_step(f"Speaker ({info_a['name']}) presenting final response...")
        if on_draft_start:
            on_draft_start(1, speaker_agent)
        
        import time
        # Simulate real-time streaming of the final approved argument under the speaker_agent
        words = re.findall(r'\s*\S+\s*', approved_arg)
        for word in words:
            if on_token:
                on_token(word, speaker_agent)
            time.sleep(0.015)

        # Trigger audio playback for the approved argument using Strategist A's voice settings
        if approved_arg and _audio_transcription_enabled():
            voice_id = "en-US-ChristopherNeural"
            panning = 0.0
            if info_a["key"] in PHILOSOPHER_LIBRARY:
                voice_id = PHILOSOPHER_LIBRARY[info_a["key"]].get("voice_id", voice_id)
                panning = PHILOSOPHER_LIBRARY[info_a["key"]].get("stereo_panning", panning)
            import streamlit as st
            speaker_speed = float(
                st.session_state.get("_dp_speaker_speed")
                or st.session_state.get("_pref_speaker_speed")
                or st.session_state.get("speaker_speed", 1.0)
                or 1.0
            )
            from audio_engine import get_audio_manager, SentenceChunker
            if get_audio_manager().is_running:
                chunker = SentenceChunker(lambda sentence: get_audio_manager().enqueue(sentence, voice_id, panning, speaker_speed))
                for word in words:
                    chunker.add_token(word)
                chunker.flush()

        trace["calls"].append(f"Speaker ({info_a['name']})")

        return {
            "text": approved_arg,
            "team_trace": trace,
            "speaker_name": info_a["name"],
            "speaker_image": info_a["image"]
        }

    def respond(
        self,
        topic,
        transcript,
        round_idx,
        strategy,
        max_words=120,
        team_mode=False,
        on_step=None,
        on_token=None,
        on_draft_start=None,
    ):
        history = "\n".join([f"{t['speaker']}: {t['text']}" for t in transcript[-5:]])
        if team_mode:
            return self._respond_with_team(
                topic,
                history,
                round_idx,
                strategy,
                max_words,
                on_step,
                on_token,
                on_draft_start,
            )

        if on_step:
            is_free = self.side == "Free Topic"
            step_msg = "Formulating philosophical response..." if is_free else "Formulating philosophical argument..."
            on_step(step_msg)
            
        task_msg = "Give your opinion on the given input. If pro/contra is relevant, acknowledge both briefly and state your view." if self.side == "Free Topic" else "Provide your philosophical argument."
        prompt = f"{self._team_context(topic, history, round_idx, strategy)}\nTask: {task_msg} Limit: {max_words} words."
        
        def stream_callback(token):
            if not hasattr(self, "_chunker"):
                def on_sentence(sentence):
                    if not _audio_transcription_enabled():
                        return
                    voice_id = "en-US-ChristopherNeural"
                    panning = 0.0
                    from config import PHILOSOPHER_LIBRARY
                    if self.key in PHILOSOPHER_LIBRARY:
                        voice_id = PHILOSOPHER_LIBRARY[self.key].get("voice_id", voice_id)
                        panning = PHILOSOPHER_LIBRARY[self.key].get("stereo_panning", panning)
                    import streamlit as st
                    speaker_speed = float(
                        st.session_state.get("_dp_speaker_speed")
                        or st.session_state.get("_pref_speaker_speed")
                        or st.session_state.get("speaker_speed", 1.0)
                        or 1.0
                    )
                    from audio_engine import get_audio_manager
                    if get_audio_manager().is_running:
                        get_audio_manager().enqueue(sentence, voice_id, panning, speaker_speed)
                from audio_engine import SentenceChunker
                self._chunker = SentenceChunker(on_sentence)
            self._chunker.add_token(token)

        res = chat_completion(
            self._system_prompt(),
            prompt, 
            provider=self.agent_provider, 
            model=self.agent_model, 
            response_model=None, 
            stream_callback=stream_callback,
            stream_generator=True
        )
        
        def ui_generator():
            full_text = ""
            for token in res:
                full_text += token
                yield token
            if hasattr(self, "_chunker"):
                self._chunker.flush()
                del self._chunker
            # Normally we clean think tags, but we just yield the text raw to the UI.
            # In single mode, the UI handles it directly, we just return the generator for the UI.
            # However, the return signature of respond should be a dict if team_mode is false,
            # but wait, we need to return the generator to ui.py so st.write_stream can consume it!
            # We'll yield a special dict at the end, or ui_generator itself will be the text.
            # Actually, `st.write_stream` returns the full joined string!
            # So `ui.py` can capture the full string and append it to the transcript itself!
        
        # We return the generator directly instead of a dictionary.
        # ui.py needs to handle it.
        return ui_generator()

def build_agents(agent_configs):
    agents = []
    for idx, cfg in enumerate(agent_configs):
        philosopher = PHILOSOPHER_LIBRARY[cfg["philosopher_key"]]
        agents.append(DebateAgent(
            key=cfg.get("philosopher_key", f"agent_{idx}"),
            name=cfg.get("display_name", philosopher["name"]),
            goal=cfg.get("goal", ""),
            style=philosopher["style"],
            philosopher=philosopher["name"],
            philosopher_stance=philosopher["stance"],
            image=philosopher["image"],
            side=cfg.get("side", ""),
            agent_provider=cfg.get("provider"),
            agent_model=cfg.get("model"),
            team_config=cfg.get("team_config", {})
        ))
    return agents

def run_debate(
    topic,
    rounds,
    player_strategies,
    agent_configs,
    max_words=120,
    team_mode=False,
    on_step=None,
    on_token=None,
    on_draft_start=None,
):
    transcript = []
    agents = build_agents(agent_configs)
    for r in range(1, rounds + 1):
        for i, agent in enumerate(agents):
            res = agent.respond(
                topic, 
                transcript, 
                r, 
                player_strategies[i], 
                max_words, 
                team_mode, 
                on_step=(
                    lambda msg, agent_name=agent.name, round_idx=r:
                    on_step(f"Round {round_idx}: {agent_name} — {msg}")
                ) if on_step else None,
                on_token=(
                    lambda token, agent=agent, round_idx=r:
                    on_token(token, agent, round_idx)
                ) if on_token else None,
                on_draft_start=(
                    lambda attempt, agent=agent, round_idx=r:
                    on_draft_start(agent, round_idx, attempt)
                ) if on_draft_start else None,
            )
            
            if team_mode:
                speaker_name = res.get("speaker_name", agent.name)
                speaker_image = res.get("speaker_image", agent.image)
                turn = {"round": r, "speaker": speaker_name, "text": res["text"]}
                if "team_trace" in res: turn["team_trace"] = res["team_trace"]
                transcript.append(turn)
                speaker_agent = TeamSpeaker(name=speaker_name, image=speaker_image, side=agent.side)
                yield {"type": "team", "agent": speaker_agent, "turn": turn, "transcript": transcript}
            else:
                # res is a generator
                def intercept_generator():
                    full_text = ""
                    for token in res:
                        full_text += token
                        yield token
                    
                    cleaned = re.sub(r'<think>.*?</think>', '', full_text, flags=re.DOTALL).strip()
                    turn = {"round": r, "speaker": agent.name, "text": cleaned}
                    transcript.append(turn)
                    
                yield {"type": "single", "agent": agent, "generator": intercept_generator(), "transcript": transcript}

def judge_debate(topic, transcript, judge_provider="", judge_model="", focus=""):
    history = "\n".join([f"{t['speaker']}: {t['text']}" for t in transcript])

    sys_prompt = SYSTEM_PROMPT
    if focus:
        sys_prompt = f"{SYSTEM_PROMPT} {focus}"

    speakers = list(dict.fromkeys(t["speaker"] for t in transcript))
    speaker_list = " vs ".join(speakers)

    prompt = (
        f"You are a strict debate judge. Evaluate this debate on: '{topic}'.\n"
        f"Speakers: {speaker_list}\n\n"
        f"--- DEBATE TRANSCRIPT ---\n{history}\n"
        f"--- END OF TRANSCRIPT ---\n\n"
        f"SCORING SCALE — apply this exactly:\n"
        f"  9-10: Exceptional (rare — outstanding logic, evidence, and rhetoric)\n"
        f"  7-8:  Good (clear, well-reasoned, mostly effective)\n"
        f"  5-6:  Average (adequate but unremarkable)\n"
        f"  3-4:  Weak (noticeable flaws, thin reasoning, or missed opportunities)\n"
        f"  0-2:  Poor (major logical errors, incoherent, or off-topic)\n\n"
        f"MANDATORY RULES:\n"
        f"1. Score each speaker on: logical validity, argument strength, counterargument handling, clarity, relevance (each 0-10).\n"
        f"2. The overall total for each speaker is the SUM of their 5 scores (max 50).\n"
        f"3. If the totals are genuinely equal, you may declare a draw — write 'Winner: Draw'.\n"
        f"4. Use the EXACT format for each speaker (no extra text on these lines):\n"
        f"[Speaker Name]: [score]/10 logical validity, [score]/10 argument strength, [score]/10 counterargument handling, [score]/10 clarity, [score]/10 relevance, [score]/50 overall total.\n"
        f"5. After the scores, write 2-3 sentences of reasoning that explain your decision:\n"
        f"   - Sentence 1: Identify the strongest argument or moment from the winner (or highlight parity if a draw).\n"
        f"   - Sentence 2: Identify the key weakness or missed opportunity from the other speaker.\n"
        f"   - Sentence 3 (optional): Explain any notable score differences between specific metrics.\n"
        f"   Format: Reasoning: [Your 2-3 sentences here].\n"
        f"6. Final line only: Winner: [Speaker Name or Draw]"
    )
    return chat_completion(
        sys_prompt,
        prompt,
        provider=judge_provider,
        model=judge_model,
        response_model=None,
        stream_generator=True,
        temperature=0.0,
    )

def aggregate_judgments(judgments):
    if not judgments:
        return None

    # 1. Average the scores first — needed as tiebreaker for split votes.
    speaker_score_sums = {}
    speaker_score_counts = {}

    for j in judgments:
        if not j or not isinstance(j, dict) or not isinstance(j.get("scores"), dict):
            continue
        for speaker, metrics in j["scores"].items():
            if not isinstance(metrics, dict):
                continue
            if speaker not in speaker_score_sums:
                speaker_score_sums[speaker] = {}
                speaker_score_counts[speaker] = {}
            for metric, val_str in metrics.items():
                if not isinstance(val_str, str):
                    continue
                try:
                    num_part = val_str.split("/")[0].strip()
                    val = float(num_part)
                    speaker_score_sums[speaker][metric] = speaker_score_sums[speaker].get(metric, 0.0) + val
                    speaker_score_counts[speaker][metric] = speaker_score_counts[speaker].get(metric, 0) + 1
                except Exception:
                    pass

    aggregated_scores = {}
    for speaker, metrics in speaker_score_sums.items():
        aggregated_scores[speaker] = {}
        for metric, total_sum in metrics.items():
            count = speaker_score_counts[speaker].get(metric, 0)
            avg_val = total_sum / count if count > 0 else 0.0
            denominator = 50 if metric == "total" else 10
            if avg_val.is_integer():
                avg_str = f"{int(avg_val)}/{denominator}"
            else:
                avg_str = f"{avg_val:.1f}/{denominator}"
            aggregated_scores[speaker][metric] = avg_str

    def _avg_total(speaker: str) -> float:
        metrics = aggregated_scores.get(speaker, {})
        val_str = metrics.get("total", "0/50")
        try:
            return float(val_str.split("/")[0])
        except Exception:
            return 0.0

    # 2. Determine winner by majority vote; break ties with averaged total score.
    winner_votes: dict = {}
    for j in judgments:
        if not j or not isinstance(j, dict):
            continue
        w = j.get("winner")
        if isinstance(w, str):
            w = w.strip()
            if w and w.lower() not in ("n/a", "error", ""):
                key = w.lower()
                if key not in winner_votes:
                    winner_votes[key] = {"name": w, "count": 0}
                winner_votes[key]["count"] += 1

    best_winner = None
    if winner_votes:
        max_votes = max(info["count"] for info in winner_votes.values())
        tied = [info["name"] for info in winner_votes.values() if info["count"] == max_votes]
        if len(tied) == 1:
            best_winner = tied[0]
        else:
            # Vote tie — use averaged total score as tiebreaker.
            totals = {name: _avg_total(name) for name in tied}
            scores_list = list(totals.values())
            if len(scores_list) >= 2 and scores_list[0] == scores_list[1] and len(set(scores_list)) == 1:
                best_winner = "Draw"
            else:
                best_winner = max(totals, key=totals.get)

    if not best_winner:
        # Fallback: no valid winner votes — compare scores directly.
        if aggregated_scores:
            totals = {s: _avg_total(s) for s in aggregated_scores}
            scores_list = list(totals.values())
            if len(set(scores_list)) == 1:
                best_winner = "Draw"
            else:
                best_winner = max(totals, key=totals.get)
        else:
            best_winner = "Draw"

    # 3. Combine reasoning
    combined_reasoning = ""
    for idx, j in enumerate(judgments):
        if j and isinstance(j, dict) and j.get("reasoning"):
            combined_reasoning += f"**Judge {idx+1}**: {j['reasoning']}\n\n"

    return {
        "winner": best_winner,
        "reasoning": combined_reasoning.strip(),
        "scores": aggregated_scores
    }

def summarize_debate(topic, transcript, judgment=None, judge_provider="", judge_model="", free_topic_mode=False):
    history = "\n".join([f"{t['speaker']}: {t['text']}" for t in transcript])
    if free_topic_mode:
        prompt = (
            f"Summarize the final public response to this free topic: '{topic}'.\n\n"
            f"Rules:\n"
            f"- Summarize ONLY the selected final argument shown in the transcript.\n"
            f"- Ignore internal team roles, candidate names, strategy labels, and decision-process details.\n"
            f"- Return EXACTLY ONE line.\n"
            f"- Prefix the line with the public speaker name only; do not include parenthetical role labels.\n"
            f"- Format: 'Speaker: One-sentence summary.'\n\n"
            f"Transcript:\n{history}"
        )
    else:
        prompt = (
            f"Summarize this debate on '{topic}'.\n\n"
            f"Rules:\n"
            f"- Reduce EACH argument/turn by each speaker to EXACTLY ONE sentence.\n"
            f"- List them in order, prefixed with the speaker's name.\n"
            f"- Do NOT write a prose paragraph. Use one line per argument.\n"
            f"- Format: 'Speaker: One-sentence summary.'\n\n"
            f"Transcript:\n{history}"
        )
    return chat_completion(
        FREE_TOPIC_SYSTEM_PROMPT if free_topic_mode else SYSTEM_PROMPT,
        prompt, 
        provider=judge_provider, 
        model=judge_model, 
        response_model=None, 
        stream_generator=True
    )
